\hypertarget{class_index_out_of_bound}{
\section{IndexOutOfBound Class Reference}
\label{class_index_out_of_bound}\index{IndexOutOfBound@{IndexOutOfBound}}
}


{\ttfamily \#include $<$Utility.h$>$}

\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\hypertarget{class_index_out_of_bound_a139671d1b3d6c7f28bfa56811727f165}{
{\bfseries IndexOutOfBound} (std::string msg)}
\label{class_index_out_of_bound_a139671d1b3d6c7f28bfa56811727f165}

\item 
\hypertarget{class_index_out_of_bound_a8cbbec1f25a774b895a4618e3c416e17}{
std::string {\bfseries getMessage} () const }
\label{class_index_out_of_bound_a8cbbec1f25a774b895a4618e3c416e17}

\end{DoxyCompactItemize}


\subsection{Detailed Description}
Thrown when an index is out of range For example, list.get(10); while list.size() == 5 raises this exception. 

The documentation for this class was generated from the following file:\begin{DoxyCompactItemize}
\item 
\hyperlink{_utility_8h}{Utility.h}\end{DoxyCompactItemize}
